version: '3.0'
services:
  edot-warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/golang/src
    container_name: edot-warehouse-svc
    volumes:
      - ../:/home/golang/src
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8084:8084
    networks:
      - edot-warehouse-network
    tty: true
  # db-svc:
  #   container_name: db-svc
  #   image: 'mariadb:latest'
  #   environment:
  #     MARIADB_DATABASE: warehouse-svc
  #     MARIADB_ROOT_PASSWORD: passroot
  #     MARIADB_USER: user_name
  #     MARIADB_PASS: user_pass
  #     TZ: Asia/Jakarta
  #   volumes:
  #     - 'userdb-vol:/var/lib/mysql'
  #   ports:
  #     - '3308:3306'
  #   networks:
  #     - edot-warehouse-network
# volumes:
#   userdb-vol:
#     driver: local
networks:
  edot-warehouse-network:
    driver: bridge